-- Human-readable client identifier, separate from the UUID primary key.
-- The UUID `id` stays untouched (it's referenced by ventas, pagos, cxc,
-- visit_notebook_items, etc. — changing it would be a large, risky
-- migration across the whole schema). This just adds a short sequential
-- number for display/reference purposes, e.g. "Client #1042".

alter table clientes
  add column if not exists client_number bigint generated by default as identity;

-- Backfill existing rows in creation order so older clients get lower numbers.
with numbered as (
  select id, row_number() over (order by fecha_registro, id) as rn
  from clientes
  where client_number is null
)
update clientes c
set client_number = numbered.rn
from numbered
where c.id = numbered.id;

create unique index if not exists clientes_client_number_idx on clientes(client_number);
